[theme]
primaryColor = "#01A89E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#e8e8e8"
textColor = "#060026"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
port = 9501

