[map_fields]
"Online.Timestamp" = [""]
"Online.Process Time (s)" = [""]
"Online.DO.PV (%)" = [""]
"Online.DO.SP (%)" = [""]
"Online.Air flow.PV (sL/h)" = [""]
"Online.Air flow.SP (sL/h)" = [""]
"Online.CO2 flow.PV (sL/h)" = [""]
"Online.CO2 flow.SP (sL/h)" = [""]
"Online.N2 flow.PV (sL/h)" = [""]
"Online.N2 flow.SP (sL/h)" = [""]
"Online.O2 flow.PV (sL/h)" = [""]
"Online.O2 flow.SP (sL/h)" = [""]
"Online.Impeller speed.PV (RPM)" = [""]
"Online.Impeller speed.SP (RPM)" = [""]
"Online.Impeller torque.PV (mNm)" = [""]
"Online.Impeller torque.SP (mNm)" = [""]
"Online.Impeller torque.SP (mNm)" = [""]
